### ISSUE TITLE
UnboundLocalError Thrown When Dataframe Filter Returns 0 Rows

### ISSUE THREAD

**Issue by blaklaybul** [elastic/eland#116]
Running `calls[calls['call_duration']>8]` returns the following error: `UnboundLocalError: local variable 'show_dimension_rows' referenced before assignment` because there are no calls that have a duration greater than 8 minutes.

From ES:
```
GET calls/_search
{
  "query": {
    "range": {
      "call_duration": {
        "gte": 8
      }
    }
  }
}
```

returns:
```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by stevedodson** [comment]
@blaklaybul I can't reproduce this:

>>> import eland as ed
>>> df = ed.DataFrame('localhost:8200', 'calls')
>>> df[df['call_duration']>8]
Empty DataFrame
Columns: [call_charges, call_duration, dialled_number, phone_number, timestamp]
Index: []

[0 rows x 5 columns]

![image](https://user-images.githubusercontent.com/7405463/73253108-c77c8780-41b3-11ea-8e9d-f25623c4f087.png)

**Comment by sethmlarson** [comment]
Going to close this due to being stale, let us know if you're still encountering this issue. Thanks!
