### ISSUE TITLE
Upgrade to pandas 1.0.1

### ISSUE THREAD

**Issue by stevedodson** [elastic/eland#124]
Now pandas 1.0.1 is released, we should look to update eland to this version.

**Comment by mesejo** [comment]
I was trying to help with this one, but when I run the tests (pytest --nbval --doctest-modules) I get:

1. ModuleNotFoundError : No module named 'eland', all the test in /docs/source/examples fail.

2. current license is non-compliant for [ml], basically all the tests related to ml also fail. This is of course because I have the free version of elasticsearch.

Any tips or work-arounds regarding both issues?

**Comment by stevedodson** [comment]
@mesejo - many thanks for the comments.

For 1. - when running the notebook tests you need a local install of `eland`. E.g.

```
python3 -m venv eland_test
source eland_test/bin/activate
pip install -r requirements-dev.txt
*python setup.py install*
pytest --nbval  --doctest-modules
```

I've updated the docs to reflect this.

For 2. we will add a better way to develop only against the basic version of elasticsearch, but for now you can test via `pytest -k 'not eland/tests/ml' --nbval --doctest-modules` to ignore the ml tests.

**Comment by Winterflower** [comment]
Adding a note about usability here:
Many users of pip simply run 
```
pip install pandas
```
which will result in them getting the latest available version, we will have incompatibility issues like the following when trying to use `eland` and `pandas` in the same env 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-c0162cb97096> in <module>
      1 # imports - these are the libraries needed to analyse the dataset
----> 2 import eland as ed
      3 from elasticsearch import Elasticsearch
      4 import pandas as pd

~/development/machine-learning-data/datasets/chocolate-bar-ratings/env/lib/python3.7/site-packages/eland/__init__.py in <module>
     25 from eland.query_compiler import *
     26 from eland.ndframe import *
---> 27 from eland.series import *
     28 from eland.dataframe import *
     29 from eland.utils import *

~/development/machine-learning-data/datasets/chocolate-bar-ratings/env/lib/python3.7/site-packages/eland/series.py in <module>
     36 import numpy as np
     37 import pandas as pd
---> 38 from pandas.io.common import _expand_user, _stringify_path
     39 
     40 import eland.plotting

ImportError: cannot import name '_stringify_path' from 'pandas.io.common' (/Users/camilla/development/machine-learning-data/datasets/chocolate-bar-ratings/env/lib/python3.7/site-packages/pandas/io/common.py)
```

**Comment by sethmlarson** [comment]
To do this we'd have to drop Python 3.5.3 (pandas v1 only supports 3.5+) but I think that is fine.
