### ISSUE TITLE
Upgrade to xgboost 1.0.1

### ISSUE THREAD

**Issue by stevedodson** [elastic/eland#133]
xgboost 1.0.1 https://pypi.org/project/xgboost/#history is now on pypi and has slightly different semantics to 0.90.

@benwtrent can add more detail

**Comment by benwtrent** [comment]
The upgrade should be trivial. From what I can tell from the docs, the external API changes that occurred should not cause many changes. 

This is the only API change I can see: https://github.com/dmlc/xgboost/pull/4541

Need to verify that the model transformers work well with that estimator.

Key file: https://github.com/elastic/eland/blob/master/eland/ml/_model_transformers.py#L228
