### ISSUE TITLE
Create Elastic Stack integration test for model transform classes

### ISSUE THREAD

**Issue by benwtrent** [elastic/eland#134]
Integration test scenario for:

- Creating models via some known data set.
   - These models should be the types that currently have serialization helpers
- Gather the predicted values and probabilities (if applicable)
- PUT the model in Elasticsearch
- Verify that ES returns the same predicated values and probabilities (within some epsilon).

**Comment by stevedodson** [comment]
@benwtrent https://github.com/elastic/eland/blob/master/eland/tests/ml/test_imported_ml_model_pytest.py gets run as part of the CI.

**Comment by benwtrent** [comment]
closing as it is already done.

I am 🐌
