### ISSUE TITLE
Change version numbering to support pip version patterns

### ISSUE THREAD

**Issue by joshdevins** [elastic/eland#138]
The current versioning scheme does not support `pip` versioning patterns. Some examples from a `requirements.txt`:

```
eland==7.*
eland>=7.0
```

Results in:

```
Could not find a version that satisfies the requirement eland==7.* (from -r requirements.txt (line 19)) (from versions: 7.5.1a2, 7.5.1a3, 7.5.1a4, 7.6.0a1, 7.6.0a2, 7.6.0a3)
No matching distribution found for eland==7.* (from -r requirements.txt (line 19))
```

Versions like `7.6.0a3` are not semantically versioned, so the only way to just `pip install` the latest is to go straight to GitHub `git+ssh://git@github.com/elastic/eland.git`, however this gets you unreleased and possibly unstable versions as well.

**Comment by sethmlarson** [comment]
If you want to install "pre-releases" with pip I believe you can use the flag `--pre` with your `python -m pip install` command and then you'll get access to the alpha releases.

**Comment by joshdevins** [comment]
@sethmlarson Ah, thanks, I didn't realise that the `X.YaN` versioning was [valid for pre-releases](https://www.python.org/dev/peps/pep-0440/#pre-releases). I prefer in this case to [use a wildcard to include pre-releases](https://pip.pypa.io/en/stable/reference/pip_install/#pre-release-versions) for this dependency only as opposed to adding `--pre` since that will apply to everything in `requirements.txt`.

I'm using`>=` now, which, somewhat surprisingly, properly installs the latest version (`7.6.0a3` in this case):

```
eland>=7.*
```

For anyone's future reference, this also works but then applies to everything:

```
pip install --pre -r requirements.txt
```
