### ISSUE TITLE
If an ES field has some missing values, eland substitutes _id for these values instead of leaving them empty

### ISSUE THREAD

**Issue by Winterflower** [elastic/eland#139]
## Eland version
`eland-7.6.0a3`
Installed through `pip`.
## Steps to reproduce

1. Create an index where a field is missing values in some documents - see example below. Some documents have an empty string for the field `BeanType`

<img width="801" alt="Screen Shot 2020-03-06 at 12 14 04 PM" src="https://user-images.githubusercontent.com/4982858/76078985-13390280-5fa4-11ea-9659-edd5c5dd30cf.png">

2. Read this index into `eland`

```
# establish connection to elasticsearch and read-in the dataset
es_client = Elasticsearch(host=ES_HOST, port=ES_PORT)
eland_df = ed.DataFrame(client=es_client, index_pattern=INDEX_NAME)
```

3. Check the dataset using `head()` and you will see that the column `BeanType` is populated with the values from the Elasticsearch `_id` field

<img width="1104" alt="Screen Shot 2020-03-06 at 12 16 08 PM" src="https://user-images.githubusercontent.com/4982858/76079131-51362680-5fa4-11ea-9061-f3331222e448.png">

**Comment by mesejo** [comment]
IMHO this is not a bug, what is being shown is the index of `eland_df` and the values of `BeanType` (the empty string).

**Comment by sethmlarson** [comment]
Yeah I think this is an unfortunate rendering of a column and not a bug.

**Comment by Winterflower** [comment]
Yes, on further inspection , you are right. The reason I was confused, because pandas appears to automatically create an integer index column, whereas eland uses the ES ids which can be quite long and ugly.
