### ISSUE TITLE
Serializing and ingesting into ES Python data structures with numpy datatypes

### ISSUE THREAD

**Issue by Winterflower** [elastic/eland#142]
Hello eland team! 👋 
This is not a bug in eland per se, but I wanted to make a note of this anyway since eland is meant to be a data science native client and we use `elasticsearch-py` as the low level transport client, this issue will likely come up in the future anyway. 

## Serialisation errors with numpy datatypes
When working with data science related datasets, it's common to use numpy to apply various kinds of transformations. As a result, the final data types that will be ingested into ES are likely to contain numpy booleans or int/floats. When we attempt to ingest these with the low-level client, we get a JSON serialisation error

```

SerializationError: ({'mal_count': 1038, 'be_count': 2080, 'label': True}, TypeError("Unable to serialize True (type: <class 'numpy.bool_'>)"))
```

I've already discussed this previously with @sethmlarson and one solution would be to implement an override in the JSON serialiser (as this example https://gist.github.com/lribeiro/7d9fbedf830a54685811f63dbbce9464 demonstrates - thanks @HonzaKral !)

Maybe we could consider handling this out of the box for our users in eland?

**Comment by sethmlarson** [comment]
I also wonder if this makes sense to be in the `elasticsearch-py` code-base, I've gotten questions on it I believe outside of eland usage. We can potentially do detection of numpy primitives if the `numpy` module is importable and if it's not importable we fallback to what we're doing now (ie nothing).

**Comment by sethmlarson** [comment]
PR to accomplish this in `elasticsearch-py`: https://github.com/elastic/elasticsearch-py/pull/1180
