### ISSUE TITLE
Support Elasticsearch queries 

### ISSUE THREAD

**Issue by m-adams** [elastic/eland#143]
As the data is being pulled from Elasticsearch, there is a whole range of search functions available that could be exposed to allow filtering of the data retrieved.
For example, analysed text and fuzzy queries could be used to identify a corpus for analysis in eland.

We could support this through something like mirroring the elasticsearch-py search functions 
https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.search
https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.msearch

That way the user could choose between the pandas compatible/mirrored functions or the Elasticsearch specific extensions.

**Comment by stevedodson** [comment]
++ on doing this, and it should be relatively easy to AND an ES query with any pandas functions - i.e. we could support pandas _and_ ES DSL queries on the same eland.DataFrame.

@sethmlarson - nice issue to get into some of the core code. Happy to help if you need?
