### ISSUE TITLE
Empty DataFrames don't have proper number of rows after .head()/.tail()

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#152]
This is caused by the `if size is not None` within `Operations.index_count()`, should we add a parameter to ignore `if size is not None` logic and ignore within `Index.__len__`? Would create a request per call to `__len__` though. 

```python
>>> df = ed.DataFrame(es, 'flights')
>>> print(df[df["Carrier"] == "nada"].tail().shape)
(5, 27)
>>> df = df._to_pandas()
>>> print(df[df["Carrier"] == "nada"].tail().shape)
(0, 27)
```

**Comment by mesejo** [comment]
Do this problem leaks to other parts of the code? Doing this:

`DataFrame(query_compiler=self._query_compiler.tail(min(n, len(self))))`

Seems to solve the issue. The above is also *semantically* equivalent to what pandas does, but in their case is handle by the numpy slicing.

**Comment by sethmlarson** [comment]
This is actually an issue with `Operations.index_count()` where it assumes the length of the index if there's a post-processing `SizeTask`. Really we shouldn't be determining the size based on the tasks, should probably be querying the index every time.
