### ISSUE TITLE
Add Pandoc to documentation instructions

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#157]
Was missing `pandoc` and took some time to figure out why documentation wasn't building. Add a note in the contributing docs on installing pandoc.

**Comment by mesejo** [comment]
Hi do you have a link pointing to how to install pandoc? The only I could find is this [this](https://zoomadmin.com/HowToInstall/UbuntuPackage/pandoc). I do not think is a reliable source, although it worked. There is the official docs, but the process described there is not very user-friendly.
