### ISSUE TITLE
Warn users about aggregations / calculations that are approximations

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#163]
ES uses some approximations to achieve massive scale, we should warn users about this especially for aggs/calcs that are susceptible to differences in value compared to the Pandas counterparts.

**Comment by V1NAY8** [comment]
- To my understanding, cardinality, median, mad and percentiles give approximations.
- So, editing the static method `_map_pd_aggs_to_es_aggs` and adding a warning message there would do.
- Shall I keep a generic message or include the agg in the warning to be more specific?
```python
>>> warning_aggs = ["cardinality","mean"]
>>> warnings.warn(f"Calculations/Aggregations on following fields {warning_aggs} are approximate", UserWarning)
```

**Comment by sethmlarson** [comment]
I was thinking more a warning within the documentation on aggregations :) much easier to implement!
