### ISSUE TITLE
Add `inference_config` to Elasticsearch model configurations

### ISSUE THREAD

**Issue by benwtrent** [elastic/eland#164]
In Elasticsearch version 7.8.0, a new required field is added to trained_model_config objects. https://github.com/elastic/elasticsearch/pull/54421

When Eland starts integrating against 7.8.0, it will need to include the appropriate inference config in the model payload. 

https://github.com/elastic/eland/blob/29af76101e01565e28e36c210eed1c0b8d27281a/eland/ml/imported_ml_model.py#L168

It should be added here. It might be as simple as adding the line:
```
"inference_config": {self._model_type: {}},
```

**Comment by sethmlarson** [comment]
An issue I ran into here is that if we unconditionally add the `"inference_config": {self._model_type: {}},` then we run into issues with ES 7.6 where this field didn't exist.
