### ISSUE TITLE
Empty Series may change type from float64 to object

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#165]
Currently we receive this warning when creating an empty pandas Series with no `dtype` specified. Happens a handful of times in `operations.py` and maybe elsewhere.

Could solve the issue by:
- Capturing the `dtype` of an empty pd.Series() somewhere (silence warning here)
- Using the `dtype=...` whenever there are no results returned

**Comment by mesejo** [comment]
Why is the testing being done again empty DataFrame / Series? What is being tested?

**Comment by sethmlarson** [comment]
@mesejo This is the warning I'm talking about. Above I mistakenly said "DataFrame" but it's actually Series:

```
>>> import pandas as pd
>>> pd.Series()
__main__:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
Series([], dtype: float64)
```

and I'm thinking something like:

```python
with (capture Deprecation warning):
    default_empty_series_dtype = pd.Series().dtype
```

and then wherever we may create an empty series without an explicit data type we set `dtype=default_empty_series_dtype`.

**Comment by mesejo** [comment]
@sethmlarson this should be done in the test or in function creating the empty Series?
