### ISSUE TITLE
Setup Intersphinx mapping to Python and Pandas

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#168]
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

**Comment by V1NAY8** [comment]
I think we pretty much did this for `dataframe.py`, `series.py` , `ndframe.py`, `groupby.py`
Example:
`:pandas_api_docs:`pandas.DataFrame.mean`

**Comment by sethmlarson** [comment]
Closing this to focus on having API documentation on elastic.co/guide
