### ISSUE TITLE
Create all aggregation helpers like .var(), .std()

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#171]
Currently we have `NDFrame.mean()`, `.min()`, etc but also need `.var()`, `.std()`, etc to be in line with Pandas.

**Comment by mesejo** [comment]
I think there is already one function in ndframe that it is mean. How is this different?

**Comment by sethmlarson** [comment]
@mesejo Ah, then we only need to implement the ones that are missing. :)

**Comment by sethmlarson** [comment]
Updated the title and issue to reflect this.
