### ISSUE TITLE
Implement DataFrame.groupby()

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#172]
See [`pandas.DataFrame.groupby()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)

Implement either as a transform or a composite aggregation.

**Comment by stevedodson** [comment]
Related to https://github.com/elastic/eland/issues/169

**Comment by V1NAY8** [comment]
@sethmlarson I will try to implement this.
- Is it mirroring pandas.DataFrame.grouby()
- What are the main features that have to be integrated initially?
- Please give me some inputs 😃

**Comment by sethmlarson** [comment]
Just a warning that this change would be a lot of work probably. I'd break it down into the following steps:

- Switch our default aggregation method to use [`composite` agg](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html) so we can paginate aggregation results by default
- Create a `GroupBy` object which holds on to a copy of the QueryCompiler with all the aggregation methods and the fields being grouped on. When calling an agg from this object should add and unpack the bucketing aggs
- Add a `.groupby()` method to `DataFrame` that returns the `GroupBy` object configured properly

I'd submit the first step as one PR and maybe can combine the second two into one PR.

**Comment by V1NAY8** [comment]
Looks good and challenging. Ill get started 😃

**Comment by V1NAY8** [comment]
@sethmlarson For the first step: I understood the concept of composite agg and pagination. 
- You mentioned **switch our default aggregation method**, does this mean edit the _metric_aggs method or create a new method?
    - Because if we change the existing method, composite agg returns buckets each unique value from one column and computes agg for that bucket! We want agg for entire column, we cant compute them from individual buckets 😐 .
    - This returns results for first time and use after_key to return the next results.
    - Should we default keep size as 100?
    - Can you give me one example of the query and how we perform groupby at elasticsearch level using composite aggs?
```bash
curl -X GET "localhost:9200/ecommerce/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
        "my_buckets":{
            "composite":{
                "size":2,
                "sources":[
                        {"total_quantity": { "terms": { "field": "total_quantity" } } },
                        {"taxful_total_price": { "terms": { "field": "taxful_total_price" } } }
                  ]
              },
                    "aggregations": {
                        "the_avg": {
                        "avg": { "field": "taxful_total_price" }
                        }
                    }
            }
    }
}
'
```
```json
{
  "took" : 137,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4675,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "my_buckets" : {
      "after_key" : {
        "total_quantity" : 1,
        "taxful_total_price" : 7.989999771118164
      },
      "buckets" : [
        {
          "key" : {
            "total_quantity" : 1,
            "taxful_total_price" : 6.989999771118164
          },
          "doc_count" : 1,
          "the_avg" : {
            "value" : 6.989999771118164
          }
        },
        {
          "key" : {
            "total_quantity" : 1,
            "taxful_total_price" : 7.989999771118164
          },
          "doc_count" : 2,
          "the_avg" : {
            "value" : 7.989999771118164
          }
        }
      ]
    }
  }
}
```

**Comment by sethmlarson** [comment]
Okay I mispoke above, we don't need to paginate by default because if we are not bucketing then aggs all return back even if there are 10000+ of them. Only use `composite` if we're using bucketing. Maybe try different defaults and see which is best for groupby() with lots of buckets.

**Comment by V1NAY8** [comment]
@sethmlarson I am progressing on this.
I have some queries:
- Currently implementing groupby for the following: `min,mean,max,std,var,nunique,sum,mad,median`. Any More functionality required?
- I am currently returning output as follows:
![image](https://user-images.githubusercontent.com/33659563/93885388-b4e62e00-fd01-11ea-9ceb-b2880cd6f253.png)

Should I display the same as pandas displays in notebook?
- What are the parameters that I need to implement? Currently pandas implements the following.
`DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=<object object>, observed=False, dropna=True)`
If yes. Please give inputs on what has to be done.
Happy to implement them 😃

**Comment by sethmlarson** [comment]
To answer your questions:
- All the single aggs are good. Should also implement for `.count()` and `.agg()/aggregate()` I believe?
- Should display the same as Pandas so will need to return a MultiIndex for the `index`.
- For options you can start with only `by` and I think `dropna` should be implementable!
  For `dropna` you can add a filter that ensures a non-null/empty value for any column you're grouping on.

**Comment by V1NAY8** [comment]
@sethmlarson 
I was able to implement all you asked except dropna:
Can you give me an example as to how to use it in Elastic Search Query for composite aggregations?
And Tasks and filters are a bit confusing from code side? Can you give me some inputs to it?

NaN values are present in ecommerce index for the column customer_birth_date.
This Query is giving empty results.
Example query:
```json
curl -X GET "localhost:9200/ecommerce/_search?pretty" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
        "my_buckets":{
            "composite":{
                "size":20,
                "sources":[
                        {"total_quantity": { "terms": { "field": "total_quantity" } } },
                        {"taxful_total_price": { "terms": { "field": "taxful_total_price" } } },
                        {"customer_birth_date": { "terms": { "field": "customer_birth_date" } } }
                  ]
              },
                    "aggregations": {
                        "the_avg": {
                        "avg": { "field": "taxful_total_price" }
                        }
                    }
            }
    }
}
'
output:
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4675,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "my_buckets" : {
      "buckets" : [ ]
    }
  }
}
```

**Comment by sethmlarson** [comment]
Closed in https://github.com/elastic/eland/pull/278 :tada:

**Comment by skyler14** [comment]
What kind of expected delay is there for this module to go into a production version?

**Comment by sethmlarson** [comment]
@skyler14 I can probably get out a release this week since all builds are betas.
