### ISSUE TITLE
Fix .var() to use Sample variance instead of Population

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#182]
Looks like one of the aggregations in the extended_metrics test suite is failing sometimes when the values are different by 11%.

**Comment by stevedodson** [comment]
There may be several issues here:

1. *Bug* - in Elasticsearch the variance is the population variance, and in `pandas.Series.var` it is the sample variance. These are different calculations, and the pandas value is identical only if `ddof=0` is set. We could resolve this, by taking the Elasticsearch value and multiplying by `N/(N-1)` - where `N` is the count returned by extended_stats. 
2. Median (50 percentile) is an approximation and so may lead to flaky tests. We can reduce the flakiness by reducing the count in the test - but need to fix 1. first.
