### ISSUE TITLE
Implement DataFrame.sample() via random_score

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#183]
The `random_score` function could be used for implementing the `.sample()` API?

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html
http://richardhallett.com/posts/random-sampling-elasticsearch/

**Comment by mesejo** [comment]
Any tips on how to implement sampling with replacement? I do have some ideas, but involved the multi-search api,  my concern is mostly regarding the performance of multi-search.

**Comment by sethmlarson** [comment]
We can start by implementing without replace=True or weights even. The use case that's really handy is getting able to pull say 1% of your production data and then use for machine learning / test data. Can always add the other cases later if they're too difficult.

Here's another resource that's interesting: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html

**Comment by mesejo** [comment]
Should this be implemented using a `SizeTask` ?

**Comment by sethmlarson** [comment]
@mesejo Yeah that's what I'd do! Add a query and sizetask.

**Comment by mesejo** [comment]
When you say query, yo mean modify the query.py file?

**Comment by sethmlarson** [comment]
I meant adding this to the query:

```
{
    "query": {
        "function_score": {
            "query": { <existing query ...> },
            "random_score": {}, 
        }
    }
}
```

and then adding a `SizeTask` to post-processing tasks to grab the number of hits you need.
If the user supplies a float we'll have to get the `count` and add a `SizeTask` based on the number of total hits. Does that make sense?

**Comment by mesejo** [comment]
I've created this:
```
    def resolve_task(self, query_params, post_processing, query_compiler):
        query_size = self._count

        query_params['query'] = {
            "query": {
                "function_score": {
                    "query": {"match_all": {}},
                    "random_score": {},
                }
            }

        }

        query_params["query_size"] = query_size

        return query_params, post_processing
```

In a SampleTask, but it seems `query_params['query']` is not a dictionary, is Query object is that correct?

**Comment by sethmlarson** [comment]
Yeah that is a `Query` object.
