### ISSUE TITLE
Consider adding typehints into the codebase

### ISSUE THREAD

**Issue by Winterflower** [elastic/eland#19]
Python has supported typehints since version 3.5 (see here https://docs.python.org/3/library/typing.html). 
Might be good to investigate if adding typehints would make the codebase a bit easier to maintain in the future?

**Comment by V1NAY8** [comment]
@sethmlarson Since, we are incrementally doing this.
Are type hints required for tests? 
Test methods would usually have return type None and pytest parameterized arguments are mostly `List[int] or List[str] or List[bool]`

**Comment by sethmlarson** [comment]
Not required for tests, only non-tests. Need to add the `py.typed` marker too.

**Comment by V1NAY8** [comment]
What does `py.typed` do, or what does it contain ? :)

**Comment by sethmlarson** [comment]
See this example project from PEP 561: 

https://github.com/ethanhs/sample-typed-package

It's an empty file that signals to mypy, etc that type hints are included in the source/dist :)
