### ISSUE TITLE
problem with a "or" in a query with Eland

### ISSUE THREAD

**Issue by penalva34** [elastic/eland#203]
when i try the same request on a pandas df load from a csv it works.
When i use a dataframe through Eland, it crashes.
Here is my request :

`r = df[(df.NNodes>100) & (df.NNodes < 250) & ((df.Comment=="BDW28") | (df.Comment=="HSW24")) & (df.Group=="dci")][['NNodes']].aggregate(['min'])
`

And the full message : 
```
...
  status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'parsing_exception', '[should] query malformed, no start_object after query name')
```

**Comment by sethmlarson** [comment]
Thanks for opening this issue, I'll take a look today!
