### ISSUE TITLE
Implement [DataFrame, Series].mode aggregation via top terms

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#215]
See the TODO comment in `operations.py`:

**Comment by V1NAY8** [comment]
@sethmlarson 
To implement `ed_df.mode()` and `ed_series.mode()`
I have an example:
- For Flights index
```json
curl -X GET "localhost:9200/flights/_search?pretty" -H 'Content-Type: application/json' -d'
{
    "size": 0,
    "aggs":{
        "terms_Cancelled": {
            "terms": {
                "field": "Cancelled"
            }
        },
        "terms_dayOfWeek": {
            "terms": {
                "field": "dayOfWeek"
            }
        }
    }
}
'
```
So the response would look like
```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "terms_dayOfWeek" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 0,
          "doc_count" : 2033
        },
        {
          "key" : 4,
          "doc_count" : 2001
        },
        {
          "key" : 2,
          "doc_count" : 1948
        },
...
      ]
    },
    "terms_Cancelled" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 0,
          "key_as_string" : "false",
          "doc_count" : 11381
        },
        {
          "key" : 1,
          "key_as_string" : "true",
          "doc_count" : 1678
        }
      ]
    }
  }
}
```
- So, I should take key with highest doc_count value which will be the mode.

- I think index="columns" and numeric_only = True/False/None should be implementable.

- I'm not sure How to do dropna 😟 

Can you acknowledge if above is correct, and give me some inputs? 😄

**Comment by sethmlarson** [comment]
Seems good, some thoughts:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html

- Use size=1 parameter for the agg 

- For dropna=False you can use the missing parameter to set a sentinel value (something wild like `@&@&NA&@&@`) then when we receive that value transform to NaN

- dropna=True is already handled

**Comment by V1NAY8** [comment]
Another doubt on size parameter
- Mode can accept multiple values 
Example:
```python
>>> pd_flights.mode()
       AvgTicketPrice Cancelled  dayOfWeek           timestamp DestCountry
0          100.020528     False        0.0 2018-01-09 07:54:19          IT
1          100.145964       NaN        NaN                 NaT         NaN
2          100.371131       NaN        NaN                 NaT         NaN
3          100.557250       NaN        NaN                 NaT         NaN
4          100.576472       NaN        NaN                 NaT         NaN
...               ...       ...        ...                 ...         ...
13054     1199.403468       NaN        NaN                 NaT         NaN
13055     1199.491317       NaN        NaN                 NaT         NaN
13056     1199.512342       NaN        NaN                 NaT         NaN
13057     1199.642816       NaN        NaN                 NaT         NaN
13058     1199.729053       NaN        NaN                 NaT         NaN

[13059 rows x 5 columns]
```
I think we need to first fetch a set of results, If multiple values are having same mode (say n), we need to fetch more set of results until we find (n-1) and construct a dataframe similar to what pandas does..

Should we write this logic in eland side, or can we do this ES Side ??

**Comment by sethmlarson** [comment]
Hmm, I need to do more research on all the various return types/shapes for `mode` but my first thought is potentially adding an extra parameter `es_size` that restricts the `terms` query to a certain maximum size to avoid dumping the entire cluster. Maybe default to 10.

If mode is ever used where there can be only one result for that column (`.agg()`) what happens in Pandas?

**Comment by V1NAY8** [comment]
- If individually we are using `mode` in `agg` 
- We get results
```python
>>> pd_df.filter(["Cancelled", "dayOfWeek", "timestamp","DestCountry"]).agg(["mode"])
	Cancelled	dayOfWeek	timestamp	DestCountry
mode	mode	mode	mode
0	False	0	2018-01-09 07:54:19	IT
```
- But when mode is used with combination of other aggs
```python
>>> pd_df.filter(["Cancelled", "dayOfWeek", "timestamp","DestCountry"]).agg(["mode","min"])
# Error
...
# ValueError: cannot combine transform and aggregation operations
```
🤔

**Comment by sethmlarson** [comment]
Hmmm, maybe we can just not support `.agg(["mode"])` and only do `.mode()`.

**Comment by V1NAY8** [comment]
Quick Update: I am progressing on this. 😃

**Comment by V1NAY8** [comment]
I have a query @sethmlarson for missing parameter in terms aggregation:
- If it is a text field => "missing": "@&@&NA&@&@" is working
- If it is a numeric or timestamp field => it is throwing `number_format_exception`

What should be the ideal "missing" for numeric, timestamp, so that it wont match with any existing document?
🤔
