### ISSUE TITLE
Type error using eland_to_pandas

### ISSUE THREAD

**Issue by hugo-pires** [elastic/eland#221]
Hello

When I try to convert an **eland dataframe** to a **pandas dataframe**, using

`pd_calls = ed.eland_to_pandas(ed_calls)`

I get the following error

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

I get also the same error on `.head()` and `.describe()` dataframe methods

Could you help me?

Thank you

**Comment by sethmlarson** [comment]
Thanks for opening this issue! Could you provide the following information:

- Version of Python and Eland: `$ python --version` and `python -m pip freeze`
- Full traceback of the error you're receiving
- Try running the queries you provided after running this:
  ```python
  import logging
  logger = logging.getLogger("elasticsearch")
  logger.addHandler(logging.StreamHandler())
  logger.setLevel(logging.DEBUG)

  # call eland_to_pandas()
  ```
  and then post the output from the `elasticsearch` logger here (with redactions if needed)

**Comment by sethmlarson** [comment]
@hugo-pires Would still like to hear the above information so we can improve this function if needed. :)

**Comment by hugo-pires** [comment]
I am very sorry, but I am no longer using this stack. Thank you anyway
