### ISSUE TITLE
DataFrame.agg() with single non-list aggregation name returns DataFrame instead of Series

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#235]
The following code produces incorrect output:

```python
from eland import DataFrame
from eland.tests.common import ES_TEST_CLIENT

df = DataFrame(ES_TEST_CLIENT, "flights")[["FlightDelayMin"]]
print("Eland")
print(df.agg("mean"))
print("Pandas")
print(df.to_pandas().agg("mean"))
```

```
Eland
      FlightDelayMin
mean       47.335171
Pandas
FlightDelayMin    47.335171
dtype: float64
```

**Comment by V1NAY8** [comment]
@sethmlarson I will try to fix this. Any inputs for me to proceed?

**Comment by sethmlarson** [comment]
Yeah, within `agg` you can detect whether it's only a string. If so you can call `getattr(self, agg)()`. Would be good to verify the agg value is a proper one like mean, mad, median, etc. Might be already a global list of those somewhere.
