### ISSUE TITLE
Improve efficiency of pandas_to_eland()

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#238]
- Use parallel_bulk() with a default parameter of 4. Make this configurable.
- Change the iterrows() loop into a generator that yields actions.
- Divide chunk_size by the number of threads.
- Only call the refresh API at the end of the function call, not on every bulk() call.

**Comment by shahrukhx01** [comment]
+1

**Comment by V1NAY8** [comment]
This can be closed.

**Comment by sethmlarson** [comment]
Closed via #279, thanks!
