### ISSUE TITLE
DataFrame.filter(axis="index", items=[...]) should preserve order of items

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#245]

**Comment by V1NAY8** [comment]
I tried elastic query for the following:
```python
ed_flights = ed.DataFrame("localhost", "flights")
ed_flights = ed_flights.filter(["1","2","0"], axis="index")
print(ed_flights)
```
So, the query goes like this:
```json
curl -X GET "localhost:9200/ecommerce/_search?pretty" -H 'Content-Type: application/json' -d'
{"query":{"bool": {"must": [{"ids": {"values": ["1", "2", "0"]}}, {"exists": {"field": "_id"}}]}}}'
```
ElasticSearch has its own way of sending the response. (sometimes ordered/ unordered)
I referred to the following:
If you can go to Conclusion section of 
https://www.elastic.co/blog/elasticsearch-query-execution-order

Q: Does the order in which I put my queries/filters in the query DSL matter?
A: No, because they will be automatically reordered anyway based on their respective costs and match costs.

@sethmlarson  If you have a workaround let me know, I'll implement this.

**Comment by sethmlarson** [comment]
If I remember correctly I was actually thinking this could be a post-processing task as opposed to something that happens on the Elasticsearch side.

**Comment by V1NAY8** [comment]
@sethmlarson 
Trying to submit PR for this, but some tests are failing because, the docker Image to setup snapshot is not allowing to run ml models, due to license expiry.
The following used to work previously!
```bash
sudo ELASTICSEARCH_VERSION=elasticsearch:7.x-SNAPSHOT eland/.ci/run-elasticsearch.sh
```
```json
{"type": "server", "timestamp": "2020-10-12T11:04:04,486Z", "level": "WARN", "component": "o.e.l.LicenseService", 
"cluster.name": "elasticsearch-7-x-SNAPSHOT-rest-test", 
"node.name": "elasticsearch-7-x-SNAPSHOT-node1", 
"message": "LICENSE [EXPIRED] ON [TUESDAY, SEPTEMBER 29, 2020].\n# IF YOU HAVE A NEW LICENSE, PLEASE UPDATE IT. OTHERWISE, PLEASE REACH OUT TO\n# YOUR SUPPORT CONTACT.\n# \n# COMMERCIAL PLUGINS OPERATING WITH REDUCED FUNCTIONALITY\n#
...
}
and
`elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'security_exception', 'current license is non-compliant for [ml]')`
```

**Comment by sethmlarson** [comment]
Try deleting ask your old containers! `docker prune` I think?

**Comment by V1NAY8** [comment]
Yeah, the command was `docker image prune -a` .
It removed all containers and images locally, retried still getting the same error.

**Comment by sethmlarson** [comment]
Try `docker container prune` too, the license is held within the container so if it expires then that container won't work anymore.

**Comment by V1NAY8** [comment]
I removed all the containers, images, volumes, networks
Just tried all the commands in this:
https://docs.docker.com/config/pruning/

I reinstall docker, then it worked 😐
