### ISSUE TITLE
Failed to parse field [trained_model]

### ISSUE THREAD

**Issue by jimazmarin** [elastic/eland#255]
I have been trying to upload a couple of models to elasticSearch and decission trees uploaded without problem but I have an error with Random Forests and XGBoost.

The error is the following: **RequestError: RequestError(400, 'illegal_argument_exception', '[1:207591826] [trained_model_definition] failed to parse field [trained_model]')**

I have tried to search in the code of eland and elasticsearch libraries but could not reach a solution. 

I leave the full error path here:

RequestError                              Traceback (most recent call last)
<ipython-input-7-cb3b8d9ac769> in <module>
----> 1 es_model = ImportedMLModel(es_client, "rf_model", rf, feature_names,  overwrite=True )

~\Anaconda3\lib\site-packages\eland\ml\imported_ml_model.py in __init__(self, es_client, model_id, model, feature_names, classification_labels, classification_weights, overwrite)
    134             body["inference_config"] = {self._model_type: {}}
    135 
--> 136         self._client.ml.put_trained_model(
    137             model_id=self._model_id, body=body,
    138         )

~\Anaconda3\lib\site-packages\elasticsearch\client\utils.py in _wrapped(*args, **kwargs)
    137                 if p in kwargs:
    138                     params[p] = kwargs.pop(p)
--> 139             return func(*args, params=params, headers=headers, **kwargs)
    140 
    141         return _wrapped

~\Anaconda3\lib\site-packages\elasticsearch\client\ml.py in put_trained_model(self, model_id, body, params, headers)
   1310                 raise ValueError("Empty value passed for a required argument.")
   1311 
-> 1312         return self.transport.perform_request(
   1313             "PUT",
   1314             _make_path("_ml", "inference", model_id),

~\Anaconda3\lib\site-packages\elasticsearch\transport.py in perform_request(self, method, url, headers, params, body)
    343 
    344             try:
--> 345                 status, headers_response, data = connection.perform_request(
    346                     method,
    347                     url,

~\Anaconda3\lib\site-packages\elasticsearch\connection\http_urllib3.py in perform_request(self, method, url, params, body, timeout, ignore, headers)
    260                 method, full_url, url, orig_body, duration, response.status, raw_data
    261             )
--> 262             self._raise_error(response.status, raw_data)
    263 
    264         self.log_request_success(

~\Anaconda3\lib\site-packages\elasticsearch\connection\base.py in _raise_error(self, status_code, raw_data)
    285             logger.warning("Undecodable raw error response from server: %s", err)
    286 
--> 287         raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
    288             status_code, error_message, additional_info
    289         )

RequestError: RequestError(400, 'illegal_argument_exception', '[1:207591826] [trained_model_definition] failed to parse field [trained_model]')

**Comment by sethmlarson** [comment]
If you're able to share the model could you try the following and post the output so we can see:

```python
import json
from eland.ml.transformers import get_model_transformer

# (Same inputs as ImportedMLModel)
transformer = get_model_transformer(
    model,
    feature_names=feature_names,
    classification_labels=classification_labels,
    classification_weights=classification_weights,
)

# Put this into the GitHub issue
print(json.dumps(transformer.transform())
```

**Comment by benwtrent** [comment]
Also, knowing the Eland version and the Elasticsearch version would help

**Comment by jimazmarin** [comment]
Hello, elasticsearch version 8.0.0 and eland version '7.7.0a1'

The output I get with the upper code is the following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-a4d89400b517> in <module>
     11 
     12 # Put this into the GitHub issue
---> 13 print(json.dumps(transformer.transform()))

~\Anaconda3\lib\json\__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

~\Anaconda3\lib\json\encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~\Anaconda3\lib\json\encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

~\Anaconda3\lib\json\encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
    180                         f'is not JSON serializable')
    181 

TypeError: Object of type Ensemble is not JSON serializable

**Comment by sethmlarson** [comment]
Sorry, need a `.to_dict()` call after `.transform()`:

```python
print(json.dumps(transformer.transform().to_dict())
```

**Comment by jimazmarin** [comment]
Te output is the following:

_IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=100000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)_

I tried changing the values but the error keeps appearing.

**Comment by sethmlarson** [comment]
@jimazmarin Maybe you can try making a script and writing to a file?

`python print_ml_model.py > upload.json`

Maybe compress that file too?

`gzip upload.json`

Then you can attach or email us the file.

**Comment by benwtrent** [comment]
Hey y'all, I did some digging. 

Here are my steps to reproduce once you have the aforementioned `upload.json`.

Compress it for shipping to Elasticsearch:
```
jq -j '{"trained_model": .}' upload.json | gzip | base64 > compressed_definition.txt
```

Create the correct JSON object using `compressed_definition.txt` and the stored feature names.
```
COMPRESSED_DEF=$(cat compressed_definition.txt); FEATURE_NAMES=$(jq '.ensemble.feature_names' upload.json); echo "{\"compressed_definition\": \"$COMPRESSED_DEF\", \"input\": {\"field_names\": $FEATURE_NAMES}, \"inference_config\":{\"classification\":{}}}" > my_model.json
```
Fun fact, the reason I am building the JSON with text replace in BASH is that `jq` complains about the arg list being too long. The compressed string can be pretty large. 

Now we have `my_model.json`
```
curl -v -X PUT -H "Content-Type: application/json" -d @my_model.json http://localhost:9200/_ml/trained_models/my_model2
```

This is assuming that you are running a local elasticsearch node.

This showed me the underlying error (which should be possible in the stacktrace of the python exception...somewhere).

The byte size size of the inflated JSON was much too large to be expanded in a smaller JVM (I had 4 GB sized node). I know 4gb seems large. But, alas, not big enough for this model size. 

So, I upped my JVM to 8GB (thank goodness that I have a pretty beefy laptop :D )

The model `put` just fine. 

So, I am guessing the underlying issue is that the node that eland is trying to upload to is way too small. 

Also, you need to double make sure that your arg list for `eland.ml.MLModel.import_model` has `es_compress_model_definition: True`. Otherwise you might get a HTTP too large error for big models.
