### ISSUE TITLE
XGBoost issue with quick fix

### ISSUE THREAD

**Issue by jimazmarin** [elastic/eland#256]
Trying to upload an XGBoost model to elastic I find de following bug:

In xgboost.py in 

_def get_feature_id(self, feature_id: str) -> int:
        if feature_id[0] == "f":
            try:
                return int(feature_id[1:])
            except ValueError:
                raise RuntimeError(f"Unable to interpret '{feature_id}'")
        f_id = self._feature_dict.get(feature_id)
        if f_id **or f_id == 0**:
            return f_id
        else:
            try:
                return int(feature_id)
            except ValueError:
                raise RuntimeError(f"Unable to interpret '{feature_id}'")_

if the f_id is 0 an error raises when the name of the feature is not a number. The little code in bold can be helpful to skip the error.

**Comment by sethmlarson** [comment]
Hey, thanks for opening this issue. I agree with the change, would you be interested in making this a PR?
