### ISSUE TITLE
Issue a warning when elasticsearch-py version doesn't match cluster major.minor version

### ISSUE THREAD

**Issue by benwtrent** [elastic/eland#276]
Elasticsearch change: https://github.com/elastic/elasticsearch/pull/63097

So, with 7.10, now all URLs that point to `_ml/inference/*` should move to `_ml/trained_models/*` to prevent getting deprecation header warnings.

**Comment by sethmlarson** [comment]
Since this a change that occurs in `elasticsearch-py` will Eland need to do anything here?

**Comment by benwtrent** [comment]
@sethmlarson 

Hot dang! I didn't know that `elasticsearch-py` supported experimental APIs. I thought the inference apis were specially supported just in Eland. 

For sure, if the change needs to happen there, then that is where it needs to be :D

**Comment by V1NAY8** [comment]
@sethmlarson 
We are using it in `mlmodel.py`
Shall I change them `inference` to `trained_models` ?

**Comment by sethmlarson** [comment]
So we shouldn't need to change anything here. I'm considering adding a warning that complains that the given `elasticsearch` library doesn't match the connected Elasticsearch cluster to avoid problems like this when using experimental features in the future :)

**Comment by sethmlarson** [comment]
Now that many machine learning features aren't experimental / beta anymore I think we can close this.
