### ISSUE TITLE
es_type_overrides should error when receiving non-existing entries

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#280]

**Comment by V1NAY8** [comment]
Does this require change to https://github.com/elastic/eland/blob/475e0f41ef869272bb6236a5eb99c3dab835fc09/eland/field_mappings.py#L542

Where If column is not in `es_type_overrides` should throw KeyError that says
```
if column not in es_type_overrides:
    raise KeyError(f"{column} specified does not exist in given dataframe")
```
🙃

**Comment by sethmlarson** [comment]
Yeah that'd be the change probably :)
