### ISSUE TITLE
Implement GroupBy.aggregate(..., dropna=True/False)

### ISSUE THREAD

**Issue by sethmlarson** [elastic/eland#290]

**Comment by V1NAY8** [comment]
- Should we add a filter to ensure that does  dropna=False? 
- Can you please give me any example of ES query?

:)

**Comment by V1NAY8** [comment]
@sethmlarson Do you have an example for this in Pandas? I cannot find one.

**Comment by sethmlarson** [comment]
This feature is implemented I believe.
