### ISSUE TITLE
Add Code Coverage 

### ISSUE THREAD

**Issue by V1NAY8** [elastic/eland#314]
We need to add code coverage to eland to see if the existing test suite covers all scenarios

Initial thoughts are using any of the below:

- By using `pytest-cov`
Ref: https://pytest-cov.readthedocs.io/en/latest/readme.html#usage

- By using `coverage`
Ref: https://coverage.readthedocs.io/en/v4.5.x/cmd.html

**Comment by sethmlarson** [comment]
Use pytest-cov, it uses coverage behind the curtains :)

**Comment by V1NAY8** [comment]
- I tried an example using `pytest-cov`, we usually get report in terminal.

- I think for github **you** need to configure `codecov`  and generate a token and upload report using it via bash.
Ref: https://docs.codecov.io/docs

So, post executing tests the report has to uploaded to codecov which should eventually show in github PR.

- - If we run the matrix for 3.* python and 7.* ES , we get lot of reports for each PR. 

Do we need to restrict the codecov report generation to 3.8 py and 7.10 ES ?? 🤔
