### ISSUE TITLE
Unable to serialize set() in pandas_to_eland

### ISSUE THREAD

**Issue by btzr-io** [elastic/eland#333]
I'm trying to use `pandas_to_eland` with a data-frame that contains some columns of a python `set` type:
```
id   name   tags
0   "zero"   { "A", "B", "C" }
1   "two"    { "A", "B", "C" }
2   "two"    { "A", "B", "C" }
```
Is there any workaround ?

> elasticsearch.exceptions.SerializationError:
> TypeError("Unable to serialize set() (type: <class 'set'>)"))

**Comment by sethmlarson** [comment]
You can convert the set into a list, elasticsearch-py's default serializer doesn't do that automatically because it's losing information.

**Comment by btzr-io** [comment]
Ok, thanks, I'll try that.
