### ISSUE TITLE
Add support for Pandas 1.2

### ISSUE THREAD

**Issue by donaghb** [elastic/eland#334]
I've been using eland for a few weeks now, and it's been very useful, but this afternoon it simply stopped working. When I tried to run import eland as ed I got this error: 
`ImportError Traceback (most recent call last)
<ipython-input-1-069d425ffac0> in <module>
      2 import pandas as pd
      3 import nltk
----> 4 import eland as ed
      5 
      6 

~\Anaconda3\lib\site-packages\eland\__init__.py in <module>
     27 )
     28 from .common import SortOrder
---> 29 from .dataframe import DataFrame
     30 from .etl import csv_to_eland, eland_to_pandas, pandas_to_eland, read_csv, read_es
     31 from .index import Index

~\Anaconda3\lib\site-packages\eland\dataframe.py in <module>
     34 from pandas.util._validators import validate_bool_kwarg
     35 
---> 36 import eland.plotting as gfx
     37 from eland.common import DEFAULT_NUM_ROWS_DISPLAYED, docstring_parameter
     38 from eland.filter import BooleanFilter

~\Anaconda3\lib\site-packages\eland\plotting\__init__.py in <module>
     23 """
     24 
---> 25 from eland.plotting._core import ed_hist_frame, ed_hist_series
     26 
     27 __all__ = [

~\Anaconda3\lib\site-packages\eland\plotting\_core.py in <module>
     16 #  under the License.
     17 
---> 18 from eland.plotting._matplotlib.hist import hist_frame, hist_series
     19 
     20 

~\Anaconda3\lib\site-packages\eland\plotting\_matplotlib\__init__.py in <module>
     23 """
     24 
---> 25 from eland.plotting._matplotlib.hist import hist_frame, hist_series
     26 
     27 __all__ = [

~\Anaconda3\lib\site-packages\eland\plotting\_matplotlib\hist.py in <module>
     19 from pandas.core.dtypes.generic import ABCIndexClass
     20 from pandas.plotting._matplotlib import converter
---> 21 from pandas.plotting._matplotlib.tools import _flatten, _set_ticks_props, _subplots
     22 
     23 from eland.utils import try_sort

ImportError: cannot import name '_flatten' from 'pandas.plotting._matplotlib.tools' (C:\Users\dbrennan\Anaconda3\lib\site-packages\pandas\plotting\_matplotlib\tools.py)`

I thought perhaps I did something wrong in my environment, so I used a different laptop, installed Eland, and when I imported eland as ed it threw the same error. 

Any ideas?

**Comment by sethmlarson** [comment]
Might be something with pandas 1.2.0? We haven't tested against the new pandas version yet, try downgrading pandas?

**Comment by donaghb** [comment]
Thanks. That worked. After I investigated why it happened it turned out I had been on 1.1.5 and without realizing it I upgraded to latest (1.2.0).

**Comment by sethmlarson** [comment]
Great, thanks for repro! Will leave this issue open to track pandas 1.2 support.
