### ISSUE TITLE
Add support for pandas v1.3.0

### ISSUE THREAD

**Issue by th0ger** [elastic/eland#359]
The latest [pandas 1.3.0](https://pandas.pydata.org/docs/whatsnew/v1.3.0.html) (July 2, 2021) fails with latest eland
```
eland = "==7.13.0b1"
pandas = "==1.3.0"
```
While importing eland:
`ImportError: cannot import name 'ABCIndexClass' from 'pandas.core.dtypes.generic'`

(Former pandas `1.2.5` works fine here.)

**Comment by sethmlarson** [comment]
Thanks for opening this! Yeah, pandas keeps changing things under our feet :)

If you'd like to contribute support for Pandas 1.3 we'd gladly review and accept such a change!

**Comment by sethmlarson** [comment]
Closed in #362
