### ISSUE TITLE
Things to tidy up in the README.md

### ISSUE THREAD

**Issue by Winterflower** [elastic/eland#36]
Some things to fix in the eland README to make usage easier:

- [x] Add supported ES versions somewhere so users know if they can safely use this

- [x] Rename this https://github.com/elastic/eland#development-setup section to "Quickstart" or something similar. Development Setup should be used in a section that's mean for people who want to contribute/make a change to the eland codebase, not for people who just want to use it. 

- [x] For Development Setup, include guidance on how to run tests for eland.

- [x] Add a Contributing section/doc that outlines the contributor policy (check the elasticsearch-py for similar guidelines)

**Comment by stevedodson** [comment]
Docs address these issues.
