### ISSUE TITLE
Add feature: DataFrame.quantile(q=, axis=1)

### ISSUE THREAD

**Issue by MnrGreg** [elastic/eland#361]
Add feature to have `.quantile(q=,axis=1)` return values to new columns rather than rows.

_axis : {0, 1, ‘index’, ‘columns’} (default 0)
0 or ‘index’ for row-wise, 1 or ‘columns’ for column-wise_

https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.quantile.html

**Comment by sethmlarson** [comment]
I think we want to keep our `dataframe~=index-pattern`, `column~=field`, `row~=document` architecture consistent.
Is it possible to accomplish what you need via `eland.quantile(...)` and `.transpose()` the result?
