### ISSUE TITLE
Release non-prerelease versions

### ISSUE THREAD

**Issue by th0ger** [elastic/eland#382]
All releases are currently marked as prereleases `*.*.*b*`.
What is required to drop the beta tag?

Having only prereleases can often end up in depdendency hell when working with `pipenv`. See [https://github.com/pypa/pipenv/issues/1760](https://github.com/pypa/pipenv/issues/1760) for `pipenv`s (poor) ability to depend on beta-only version. Also see [Black](https://github.com/psf/black/issues/517) for a similar case.

**Comment by V1NAY8** [comment]
Hi @th0ger I think We are yet to complete the https://github.com/elastic/eland/milestone/2

Then We will have a stable release.

I am working on Support aggregations on scripted fields task already.

**Comment by th0ger** [comment]
Thanks @V1NAY8, appreciate it.
Seems you are pragmatic about the amount of required features needed to have a first stable release.
(Black has taken more than 3 years to get out of beta!)
