### ISSUE TITLE
feature request: setting scroll & size in query

### ISSUE THREAD

**Issue by falcorocks** [elastic/eland#388]
Hi all,
thanks for this library, it was very much needed!!!

I have roughly 150GB of data in elasticsearch and I need to perform a (time) range query.

This is my query:
```python
# dataframe is an eland dataframe
dataframe = dataframe.es_query(
            {
                "range": {
                    range_field: {
                        "gte": start_time_isoformat,
                        "lte": end_time_isoformat,
                    }
                }
            }
        )
```

The problem is that the query took a lot of time and the program ended up crashing at night (likely an OOM error due to something unrelated that I do later on the dataframe). Anyways unfortunately it seems I don't have logs.
When using elasticsearch python library I can set `scroll` and `size` parameters like this:
``` python
es.search(index='test', body=body, scroll='2m', size=50)
```

but from the docs it does not seem like this option is available on eland right now.

- is scroll/size the solution I'm looking for?
- do you have any suggestions to increase the transfer speed?
- how/where is the speed of transfer regulated by eland?

**Comment by sethmlarson** [comment]
Glad you're finding Eland useful! :tada:

You can use [`eland.common.DEFAULT_SEARCH_SIZE`](https://github.com/elastic/eland/blob/main/eland/common.py) to modify the amount of records returned per call to `.search()` or `.scroll()`. I believe this solves your issue, closing for now. Let me know if this isn't the solution you're looking for.
