### ISSUE TITLE
Push eland Docker images with every version release

### ISSUE THREAD

**Issue by joshdevins** [elastic/eland#407]
With the recently added Dockerfile (#405) for building a Docker image from the current/local eland, we introduce the ability to run eland installed scripts without installing eland or any prerequisites. This still requires building a local Docker image though. It would be nice to avoid this and simply make available a public Docker image from the Elastic Docker repository. This would make running scripts like uploading HuggingFace transfomer models a very simple one command, with no installation or builds necessary.

This would mean hooking the Docker build into the release process, and being able to push the image to the Elastic public Docker repository.

**Comment by mjonas87** [comment]
Second! This would make it a lot easier to include in our Docker Compose ecosystem as well.
