### ISSUE TITLE
How to search exact index (not index pattern) in elasticsearch eland?

### ISSUE THREAD

**Issue by everestial** [elastic/eland#430]
This is issue reading exact elasticsearch index. The elasticsearch python api client is able to read the data for the index but eland is not. The reason being eland searches the given index name as wildcard and I am running into `ReadTimeouterror` because I do not have permission to read the indexes for long time.

The issue is documented in detail in stackoverflow question. I did not get any response and had to post it here. 

https://stackoverflow.com/questions/70685986/how-to-search-exact-index-not-index-pattern-in-elasticsearch-eland-updated

**Comment by sethmlarson** [comment]
Searching an exact index only requires passing the exact index name, no wildcards are used:

```python
import eland as ed
from elasticsearch import Elasticsearch

client = Elasticsearch(...)

client.index(index="test", document={"should": "seethis"})
client.index(index="test1", document={"should": "notseethis"})
client.index(index="1test", document={"should": "notseethis"})
client.indices.refresh(index="*test*")

df = ed.DataFrame(client, es_index_pattern="test")
print(df.to_pandas())
```

The output of the above is this as expected:

```python
                       should
SNTTnH4BRC8cqQQMds-V  seethis
```

The `pattern` word in the option doesn't mean we're using wildcards, it's the pattern that we're sending to Elasticsearch in the `search` and index APIs.

**Comment by sethmlarson** [comment]
Going to close this as resolved.
