### ISSUE TITLE
Conflicting types warning when consuming `metricbeat-*` indices data

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/eland#431]
Few of the fields in the standard metricbeat mapping cause eland to display the following warning:
```
/usr/local/lib/python3.7/dist-packages/eland/field_mappings.py:324: UserWarning: Field kubernetes.system.cpu.usage.nanocores has conflicting types ('double', None) != long
  UserWarning,
```

The code:
```python
import eland as ed
from elasticsearch import Elasticsearch

es = Elasticsearch(
    hosts="https://xyz:9243",
    basic_auth=("aaa", "bbb")
    )

df = ed.DataFrame(es, es_index_pattern="metricbeat-*")
```

**Comment by sethmlarson** [comment]
Thanks for reporting this. I'm wondering if the field being mentioned was added recently and so some indices have the field and some don't? Could you post the mappings for the earliest `metricbeat-*` index and the latest one too?

**Comment by michaelhyatt** [comment]
Good point, I think this is what is going on here. The earliest index is `metricbeat-7.10.0-2021.03.10-000105`

The mapping is attached.
[mapping.json.zip](https://github.com/elastic/eland/files/7999249/mapping.json.zip)

**Comment by pquentin** [comment]
There's not much we can do about this, unfortunately. The warning is working as intended to alert you of a potential problem, but it's not a bug in Eland itself.
