### ISSUE TITLE
DeprecationWarning: The 'body' parameter is deprecated for the 'search' API

### ISSUE THREAD

**Issue by th0ger** [elastic/eland#447]
Eland throws:

> /lib/python3.8/site-packages/eland/operations.py:1649: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
>     resp = client.search(body=body)

Please use `es.search(query={...})` instead of `es.search(body={"query": {...}})` according to https://github.com/elastic/elasticsearch-py/issues/1698.

eland version `7.14.0b1`

**Comment by pquentin** [comment]
The body parameter was added back to the Python client in elasticsearch-py 8.12.0, see https://github.com/elastic/elasticsearch-py/pull/2383 for details. This means this warning is also gone.
