### ISSUE TITLE
Should Eland work for locally installed ELK? We're getting errors with the most basic example.

### ISSUE THREAD

**Issue by jt0dd** [elastic/eland#453]
The example code published officially only shows an example of connecting to ELK hosted in a cloud instance. We're trying to use a locally running instance. Version 8.1.1

---

### Full details:

We installed ELK in docker based on [this example](https://gist.github.com/ionutale/2862aa94f7c72bd9e77cd2f239172efd). Like:

    docker run -d --name elasticsearchdb --net es-stack-network -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.8.13
    
    docker run -d --name kibana-es-ui --net es-stack-network -e "ELASTICSEARCH_URL=http://elasticsearchdb:9200" -p 5601:5601 kibana:6.8.13

We then set up Elastic with the basic built-in data sets, including the flights dataset offered by default.

Then we tried using [Eland](https://community.elastic.co/events/details/elastic-emea-virtual-presents-introduction-into-eland-a-python-package-to-analyse-explore-and-manipulate-elasticsearch-data/) to pull that data into a dataframe, and I think we're following the [documentation](https://eland.readthedocs.io/en/latest/reference/api/eland.DataFrame.html#eland.DataFrame) correctly.

But with the code:

        import eland as ed
        index_name = 'flights'
        ed_df = ed.DataFrame('localhost:9200', index_name)
    
we get this error:
    
    File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elastic_transport\client_utils.py:198, in url_to_node_config(url)
        192     raise ValueError(f"Could not parse URL {url!r}") from None
        194 if any(
        195     component in (None, "")
        196     for component in (parsed_url.scheme, parsed_url.host, parsed_url.port)
        197 ):
    --> 198     raise ValueError(
        199         "URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')"
        200     )
        202 headers = {}
        203 if parsed_url.auth:
    
    ValueError: URL must include a 'scheme', 'host', and 'port' component (ie 'https://localhost:9200')

So when we add `http://`, like so:

        import eland as ed
        index_name = 'flights'
        ed_df = ed.DataFrame('http://localhost:9200', index_name)

We get this error:

    File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\elastic_transport\_node\_http_urllib3.py:199, in Urllib3HttpNode.perform_request(self, method, target, body, headers, request_timeout)
        191         err = ConnectionError(str(e), errors=(e,))
        192     self._log_request(
        193         method=method,
        194         target=target,
       (...)
        197         exception=err,
        198     )
    --> 199     raise err from None
        201 meta = ApiResponseMeta(
        202     node=self.config,
        203     duration=duration,
       (...)
        206     headers=response_headers,
        207 )
        208 self._log_request(
        209     method=method,
        210     target=target,
       (...)
        214     response=data,
        215 )
    
    ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))

So I thought, well, maybe it's serving on HTTPS by default for some reason, maybe not related but in the logs I saw:

    05T17:17:04.734Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.18.0.3:9200, remoteAddress=/172.18.0.1:59788}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[21683dc12cff][transport_worker][T#14]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"XuzqXMk_QgShA3L5HnfXgw","elasticsearch.node.id":"H1CsKboeTyaFFjk2-1nw2w","elasticsearch.node.name":"21683dc12cff","elasticsearch.cluster.name":"docker-cluster"}

so I try replacing `http` with `https` and get this error:

    TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1129)))

So I look up this error and find [this thread][1] which says do something like:

    import ssl
    from elasticsearch.connection import create_ssl_context
    
    ssl_context = create_ssl_context(<use `cafile`, or `cadata` or `capath` to set your CA or CAs)
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    
    es = Elasticsearch('localhost', ssl_context=context, timeout=60

But this isn't helpful because Eland handles `elasticsearch` instancing internally, I'm not controlling that.

This is a very basic scenario, so I'm sure the solution must be much simpler than all this. What can I do to make this work?

  [1]: https://github.com/elastic/elasticsearch-py/issues/712

**Comment by sethmlarson** [comment]
Thanks for opening this issue, we definitely need to update our documentation on the Eland side to point to self-managed with generated certificates which is common for 8.0 and onwards.

For now I can point you towards [the documentation on how to configure the Python Elasticsearch client for this situation](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connect-self-managed-new). Let me know if there's confusion on any of the steps outlined there, this documentation is relatively freshly written so could benefit from feedback.
