### ISSUE TITLE
Is it possible to process hundreds of millions of documents using Eland?

### ISSUE THREAD

**Issue by igaloly** [elastic/eland#471]
I have 100 million documents stored in Elasticsearch.
Each document has a field named `vector` with the type `dense_vector`.
I want to calculate the mean vector of this bucket.
Is it an operation that's recommended by Eland?

**Comment by pquentin** [comment]
Sorry for the delay! No, it would be better to use a scripted_metric aggregation for this, see my answer in https://discuss.elastic.co/t/getting-aggregate-statistics-about-a-dense-vector-field/268694/5?u=quentin_pradet.
