### ISSUE TITLE
elasticsearch.BadRequestError: BadRequestError(400, 'x_content_parse_exception', '[1:22] unknown field [ner]')

### ISSUE THREAD

**Issue by johnny00013** [elastic/eland#490]
I tried to use the same code to upload the model to Elasticsearch (version 7.16) and go the following error
elasticsearch.BadRequestError: BadRequestError(400, 'x_content_parse_exception', '[1:22] unknown field [ner]')

**Comment by sethmlarson** [comment]
Are you trying to upload an NLP model? If so, those are only available in Elasticsearch 8.0 and later.
