### ISSUE TITLE
Is it possible to make the calls async?

### ISSUE THREAD

**Issue by DeepTitan** [elastic/eland#491]
I have 180,000 rows that I need to pull down fairly quickly. Would it be possible to extend functionality so that eighteen 10,000 record calls could be made simultaneously? Love the repo btw, I wish I would've found it even earlier!

**Comment by pquentin** [comment]
Sorry for the delay! There are no current plans to pull batches in parallel. For large datasets, I'd recommend using the API introduced in response https://github.com/elastic/eland/issues/345.
