### ISSUE TITLE
How to solve TLS error when using the eland_import_hub_model

### ISSUE THREAD

**Issue by OneZe1023** [elastic/eland#492]
When I using the following command, 
`$ eland_import_hub_model \
  --url http://localhost:9200/ \
  --hub-model-id elastic/distilbert-base-cased-finetuned-conll03-english \
  --task-type ner \
  --start`
it shows the following error message
`elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)))`

Any idea on how to solve this issue?

Thanks!

**Comment by ybgirgin3** [comment]
how did you solve this issue ? @OneZe1023

**Comment by OneZe1023** [comment]
I am kinda forget what exactly I did that solve the problem. I have tried to update the es, kibana, and reladted python library to version 8.3.1. I also change the SSL setting (something like this in ES) to false. I seems that by default, it will use the https://localhost:9200.

Hope these will help. @ybgirgin3

**Comment by ybgirgin3** [comment]
Oh thanks. I'll give it a try 🤝
