### ISSUE TITLE
 How to download only desired entry rows from Eland?

### ISSUE THREAD

**Issue by IavTavares** [elastic/eland#510]
Currently, if I want to create a dataframe with specific entries from an index, using Eland, I must first download a dataframe with all the columns, and then filter them out, locally... this is hardly desirable in terms of CPU and RAM local usage. Is there a way to push the filtering to the ES nodes instead, and simply download the already filtered dataframe?

**Comment by sethmlarson** [comment]
You can filter out which columns to download either using the `columns=[...]` parameter on the `DataFrame` constructor or you can use the `DataFrame.filter()` method to cut down on the columns to be requested before calling `.to_pandas()`.
