### ISSUE TITLE
Doc not readable

### ISSUE THREAD

**Issue by AndreaPrati98** [elastic/eland#530]
Hi everyone, 

it's been days that I am trying to access the documentation at this link: [eland.readthedocs.io/](eland.readthedocs.io/).

This is the response: 

![Screenshot 2023-04-24 at 12 16 19](https://user-images.githubusercontent.com/62189267/233968320-875dca26-48f9-42f0-a201-f90fd6b7bbd6.png)

**Comment by davidkyle** [comment]
Try https://eland.readthedocs.io/en/latest/index.html

I followed the link to *[Eland DataFrame API documentation](https://eland.readthedocs.io/en/latest/reference/dataframe.html)* in the [README](https://github.com/elastic/eland#dataframes-in-eland)

**Comment by AndreaPrati98** [comment]
Ok, got it, thank you. 

I thought it would have been still worth it to point that out that if someone tries to follow: https://eland.readthedocs.io/ it ends up https://eland.readthedocs.io/en/v8.7.0/.

**Comment by davidkyle** [comment]
👍 It is a valid point @AndreaPrati98 thanks for opening the issue. 
You're right that the re-direct needs updating

**Comment by sethmlarson** [comment]
Okay, I've for now changed the default version to latest. v8.7.0 isn't buildable since pandas dropped support for Python 3.7. Once we publish a new release it'll swap back to using the latest release explicitly as the default version. Going to close this one for now.
