### ISSUE TITLE
Change ML instance configuration

### ISSUE THREAD

**Issue by temiwale88** [elastic/eland#538]
Not sure if this can be routed to a more appropriate space but how do we change the ML instance for Elastic Cloud deployments? For my eland experiment, I am currently assigned "**aws.es.ml.c5d**" (costly) but I'd like to change it to "**aws.es.ml.m6gd**". In my search to change instance configuration, I'm led to this [doc](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-login.html) that requires me to login to a URL I can't find. 

Thanks!

**Comment by davidkyle** [comment]
Hi @temiwale88 

> Not sure if this can be routed to a more appropriate space

Try the elastic discuss forum and use the tag `elastic-cloud` https://discuss.elastic.co/tag/elastic-cloud
