### ISSUE TITLE
A bit hard to find and run eland_import_hub_model on Windows

### ISSUE THREAD

**Issue by sakurai-youhei** [elastic/eland#551]
Right after `pip install eland`, neither `python -m eland` nor `eland_import-hub-model` works on Windows.

```shell
C:\Users\YouheiSakurai>python -m eland
C:\Program Files\Python311\python.exe: No module named eland.__main__; 'eland' is a package and cannot be directly executed

C:\Users\YouheiSakurai>eland_import_hub_model
'eland_import_hub_model' is not recognized as an internal or external command,
operable program or batch file.
```

1. `python -m eland` doesn't work because no of `eland.__main__`.
2. `eland_import-hub-model` doesn't work because [scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) is used instead of [console_scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point) in `setup.py`.

![image](https://github.com/elastic/eland/assets/721858/78d32cdd-8cee-4512-8a5c-d86fa81d5a9f)

As the above picture shows, `eland_import_hub_model` is not executable on Windows due to no file extension like `.exe`.

I will open a PR to solve this hassle on Windows.

**Comment by mwrothbe-intc** [comment]
Anxiously waiting on this fix.  Hoping it will unblock me on Windows.  THANKS!!

**Comment by sakurai-youhei** [comment]
As response to https://github.com/elastic/eland/pull/557#pullrequestreview-1525783718:

The following flake8 lint errors proves that noxfile covers `eland/cli/eland_import_hub_model.py` properly.
https://github.com/elastic/eland/actions/runs/5540963903/jobs/10113737631?pr=559

**Comment by xuanyuanbao** [comment]
I also has error。what i can do make it work?

**Comment by xuanyuanbao** [comment]
> I also has error。what i can do make it work?

## oh,thanks me, I have resolve this shit problem，it my code instead to eland_import_hub_model in shell，it works where your computer operation system is Windows。

## secondly, my elasticsearch version is 8.6.0, but elasticsearch 8.7.0 also works

```
import elasticsearch
from pathlib import Path
from eland.ml.pytorch import PyTorchModel
from eland.ml.pytorch.transformers import TransformerModel

# Load a Hugging Face transformers model directly from the model hub
tm = TransformerModel("sentence-transformers/clip-ViT-B-32-multilingual-v1", "text_embedding")

# Export the model in a TorchScrpt representation which Elasticsearch uses
tmp_path = "models"
Path(tmp_path).mkdir(parents=True, exist_ok=True)
model_path, config, vocab_path = tm.save(tmp_path)

ca_certs_path = "../app/conf/ca.crt"
# Import model into Elasticsearch
es = elasticsearch.Elasticsearch("https://elastic:AdZ4x8NxzC23i=A_jCrF@127.0.0.1:9200",
                                 ca_certs=ca_certs_path,
                                 verify_certs=True, timeout=300)  # 5 minute timeout

ptm = PyTorchModel(es, tm.elasticsearch_model_id())
ptm.import_model(model_path=model_path, config_path=None, vocab_path=vocab_path, config=config)

```
