### ISSUE TITLE
Conda downgrades Elasticsearch when installing eland

### ISSUE THREAD

**Issue by srikanthmanvi** [elastic/eland#672]
`conda install conda-forge::eland` downgrades Elasticsearch.

![image (2)](https://github.com/elastic/eland/assets/6982768/ecc46105-c22a-45ad-82c4-f4b457999531)

**Comment by pquentin** [comment]
I have packaged all recent versions of Eland on conda-forge. I am still surprised by the above screenshot, since 8.0 has been on conda-forge since February 2022, so something else is going on. Happy to reopen if I get evidence that things are still wrong.
