### ISSUE TITLE
Text expansion not supported when using 3rd party models

### ISSUE THREAD

**Issue by shahkrohan** [elastic/eland#704]
File "/env/lib/conda/rohan-retrieval/lib/python3.10/site-packages/eland/ml/pytorch/transformers.py", line 665, in __init__
    self._traceable_model = self._create_traceable_model()
  File "/env/lib/conda/rohan-retrieval/lib/python3.10/site-packages/eland/ml/pytorch/transformers.py", line 1029, in _create_traceable_model
    raise TypeError(
TypeError: Unknown task type text_expansion, must be one of: fill_mask, ner, pass_through, question_answering, text_classification, text_embedding, text_expansion, text_similarity, zero_shot_classification

this is from [here](https://github.com/elastic/eland/blob/56a46d0f85c20b08f7e79cae55ca1dca3500f4ac/eland/ml/pytorch/transformers.py#L74). would appreciate if you fixed this ASAP

**Comment by pquentin** [comment]
Thanks! It looks like @davidkyle may have missed that in #520? This is indeed the only task type missing in `_create_traceable_model`.

**Comment by rohankshah04** [comment]
#706

**Comment by davidkyle** [comment]
Closed by #740
