### ISSUE TITLE
Add nbval to CI for jupyter notebook tests

### ISSUE THREAD

**Issue by Winterflower** [elastic/eland#88]
More information about nbval here: 
https://pypi.org/project/nbval/

**Comment by V1NAY8** [comment]
- What has to be done as part of this ?
- As of now `docs/source/examples` as `.ipynb` notebooks
- Should we add `session.run("pytest", "--nbval", *(session.posargs or ("docs/sources/examples/",)))` at line 104 in `noxfile.py`

**Comment by sethmlarson** [comment]
Pretty sure this hasn't been picked up yet. If you're like to give it a spin I think @Winterflower wouldn't mind :)
